spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    username: root
    password: root
  data:
    rest:
      base-path: /data-api
server:
  port: 8080
taco:
  orders:
    pageSize: 10
